name: Build RPM
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        releasever: [rawhide, 44, 43, 42]
        arch: [x86_64, aarch64, i386]
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-22.04-arm' || 'ubuntu-latest' }}
    container:
      image: ghcr.io/terrapkg/builder:f${{ matrix.releasever }}
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Checkout Ultramarine repository
        uses: actions/checkout@v6
        with:
          repository: Ultramarine-Linux/packages
          fetch-depth: 0
      - name: Checkout Mock Configs
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          path: mock-configs

      - name: Set up git repository
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Include custom build template instead of package default
        run: cp -v mock-configs/ultramarine*.tpl /etc/mock/templates/

      - name: Build with Andaman
        run: anda build ultramarine-mock-configs -c mock-configs/ultramarine-${{ matrix.releasever }}-${{ matrix.arch }}.cfg

      - name: Generating artifact name
        id: art
        run: |
          NAME=ultramarine-mock-configs-${{ matrix.arch }}-${{ matrix.releasever }}
          x=${NAME//\//@}
          echo "name=$x" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v6
        with:
          name: ${{ steps.art.outputs.name }}
          compression-level: 0 # The RPMs are already compressed :p
          path: |
            anda-build/rpm/rpms/*
            anda-build/rpm/srpm/*
